// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcrItYTXM8fMMvZ6xspovBBe3LEIrCSZE',
    appId: '1:152610794945:web:d106ce18f3acf7dd865340',
    messagingSenderId: '152610794945',
    projectId: 'wash-mesh-92883',
    authDomain: 'wash-mesh-92883.firebaseapp.com',
    storageBucket: 'wash-mesh-92883.appspot.com',
    measurementId: 'G-W2QVQ1BX3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH55sKqKF3QurscJu1CtyvQxwBYIc_mLY',
    appId: '1:152610794945:android:dce043bafc5122b9865340',
    messagingSenderId: '152610794945',
    projectId: 'wash-mesh-92883',
    storageBucket: 'wash-mesh-92883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByl6NLUDx1c01NQOc__MyjfxAwxpPUT4A',
    appId: '1:152610794945:ios:e3565d8600b8bd64865340',
    messagingSenderId: '152610794945',
    projectId: 'wash-mesh-92883',
    storageBucket: 'wash-mesh-92883.appspot.com',
    iosClientId: '152610794945-o05amro6k5e0imsnjdo1judbcpmm4pg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.washMesh',
  );
}
